defaults: &defaults
  adapter: postgresql
  username: pguser
  password: pguser
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  database: delhi_airport_development
  <<: *defaults

test:
  database: delhi_airport_test
  <<: *defaults

# production:
#   url: <%= ENV['DATABASE_URL'] %>